#
###################################
# Site wide configuration
####################################
#
title: Kunal's Blog
email:
description: Blog about my experiences with data and other technologies.
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Toronto
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Data Musings 
  avatar: kunal.png
  job: "Making stories with Data"
  # bio: "Ideas and other geeky stuff"
  email:
  disqus-shortname:
  twitter: _kunalkohli
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: kunalkohli
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: kunal-kohli-a8815b80
